swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /v1.0

paths:
  /watering/{seconds}:
    post:
      summary: Waters the plants
      description: Opens the ventile for the specified time (in seconds)
      operationId: classes.gardenbot-api.water_plants
      produces:
        - text/plain;
      responses:
        200:
          description: watering response
          schema:
            type: string
          examples:
            "text/plain": "Watering the plants..."
      parameters:
        - name: seconds
          in: path
          description: Time in seconds, the plants are supposed to be watered
          required: true
          type: string
        - name: API-Key
          in: header
          type: string
          required: true
  /check:
    post:
      summary: Checks whether the soil is wet or not
      description: Checks wether the soil is wet or not
      operationId: classes.gardenbot-api.check_moisture
      produces:
        - text/plain;
      responses:
        200:
          description: watering response
          schema:
            type: string
          examples:
            "text/plain": "Watering the plants..."
      parameters:
        - name: API-Key
          in: header
          type: string
          required: true
  /history:
    get:
      summary: Returns watering activities
      description: Returns the watering activities of the last 5 days
      operationId: classes.gardenbot-api.get_data
      produces:
      - application/json;
      responses:
        200:
          description: history response
          schema:
            type: string
          examples:
            "text/plain": "Showing the activity log"
      parameters:
        - name: API-Key
          in: header
          type: string
          required: true
  /waterstatus:
    get:
      summary: Returns watering activities
      description: Returns true, if there's enough water in the tank, otherwise false
      operationId: classes.gardenbot-api.get_water_status
      produces:
      - application/json;
      responses:
        200:
          description: history response
          schema:
            type: string
          examples:
            "text/plain": "Showing water status"
      parameters:
        - name: API-Key
          in: header
          type: string
          required: true